### ISSUE TITLE
Teste 10 com nota 1/2

### ISSUE THREAD

**Issue by rafaelsms** [VFerrari/MC346#4]
Para quem estuda vendo sua resolução, o [teste 10](https://github.com/VFerrari/MC346/blob/fdd0ef8089d14daf3931be5b8b0b2e0b582f7da3/Python/Exercicios/aula20.py#L4) está errado pois sua implementação expande todo o iterator em uma lista, prática evitada em Python 3.

Uma possível solução usando _generator_ é:
```python
>> def norep(iterator):
...     ultimo = next(iterator)
...     yield ultimo
...     for x in iterator:
...             if x != ultimo:
...                     ultimo = x
...                     yield ultimo
... 
>>> for x in norep(iter('aaaaabbbbbccccccddddddddaaaaaaaa')):
...     print(x)
... 
a
b
c
d
a
>>>
```

Que utiliza laziness, não passando necessariamente por todo o iterator inicial. Não quebrando, por exemplo, em um iterator circular.

**Comment by VFerrari** [comment]
Eu pessoalmente ficava meio confuso se ele pedia generators ou iterators. Então na maioria que pedia iterators eu fiz desse jeito, o que pode estar errado. Tem uns 5 exercícios desses na aula 19.

**Comment by rafaelsms** [comment]
Generator serve não só mas também para criar iterators. Torna o código bem mais curto, pessoalmente acho bonitinho, apesar de ser esquisito guardar não só as variáveis mas também o último ponto de execução no código.

O que quero dizer:
```python
...     ultimo = next(iterator)
...     yield ultimo # executa na primeira vez e entra no laço abaixo
...     for x in iterator:
...             if x != ultimo:
...                     ultimo = x
...                     yield ultimo # aqui ele "retorna" o último, nas próximas chamadas next, continua dentro desse laço, de onde parou
```
